# Generated by Django 5.1.6 on 2025-02-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moodgramapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_image",
        ),
    ]
